name: Deploy carlteck to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save SSH Key
        run: |
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" | base64 --decode > key.pem
          chmod 600 key.pem

      - name: SSH into VPS and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} << 'EOF'
            set -e
            PROJECT_DIR=/root/carlteck-website

            cd $PROJECT_DIR
            git pull origin main

            npm install
            npm run build

            pm2 delete carlteck || true
            pm2 start npm --name "carlteck" -- start

            pm2 save
            sudo systemctl restart nginx
          EOF
